# Generated by Django 5.0.8 on 2024-08-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='fotoauto',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='modeloauto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.DeleteModel(
            name='FotoAuto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='ModeloAuto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
